webtalk_init -webtalk_dir C:\\Users\\estra\\Desktop\\proyectos_vivado\\VentanaDeslizante\\VentanaDeslizante.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-01-23 18:53:09" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "25q6a7g7b7umcj2r6hf2l8p8hn" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.092 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1611421981980" -context "sdk\\\\bsp/1611421981980"
webtalk_add_data -client sdk -key hwid -value "1609154908110" -context "sdk\\\\bsp/1611421981980"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1611421981980"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1611421981980"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1611421981980"
webtalk_add_data -client sdk -key uid -value "1611422201355" -context "sdk\\\\application/1611422201355"
webtalk_add_data -client sdk -key hwid -value "1609154908110" -context "sdk\\\\application/1611422201355"
webtalk_add_data -client sdk -key bspid -value "1611421981980" -context "sdk\\\\application/1611422201355"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1611422201355"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1611422201355"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1611422201355"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1611422201355"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1611422201355"
webtalk_add_data -client sdk -key Procused -value "psu_cortexa53" -context "sdk\\\\application/1611422201355"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1611424389081"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1611424389081"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1611424389081"
webtalk_add_data -client sdk -key DebugCount -value "3" -context "sdk\\\\bsp/1611424389081"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1611424389081"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1611424389081"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1611424389081"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1611424389081"
webtalk_transmit -clientid 141148371 -regid "" -xml C:\\Users\\estra\\Desktop\\proyectos_vivado\\VentanaDeslizante\\VentanaDeslizante.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\estra\\Desktop\\proyectos_vivado\\VentanaDeslizante\\VentanaDeslizante.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\estra\\Desktop\\proyectos_vivado\\VentanaDeslizante\\VentanaDeslizante.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
